Repository Interacao-Humano-Computador/2020.1-SEI, pull requests merged in 2020-10, with the labels that each got.

#45 Perfil de usuário
  docs/assets/css/home.css
  docs/assets/images/user_profile/age.png
  docs/assets/images/user_profile/difficulties.png
  docs/assets/images/user_profile/familiarity.png
  docs/assets/images/user_profile/frequency.png
  docs/assets/images/user_profile/fundings.png
  docs/assets/images/user_profile/gender.png
  docs/assets/images/user_profile/language.png
  docs/assets/images/user_profile/profission.png
  docs/assets/images/user_profile/region.png
  docs/assets/images/user_profile/used.png
  docs/use_context/user_profiles.md
Labels: Documentação

#46 Personas
  docs/assets/images/personas/persona_dandara_mara.png
  docs/assets/images/personas/persona_getulio_entulho.png
  docs/assets/images/personas/persona_jose_augusto.png
  docs/assets/images/personas/persona_maria_antonieta.png
  docs/assets/images/personas/persona_ricardo_perone.png
  docs/use_context/personas.md
Labels: Documentação

#50 Criação do documento da sprint 3
  docs/_sidebar.md
  docs/meeting/PC1/sprint_0.md
  docs/meeting/PC1/sprint_1.md
  docs/meeting/PC2/sprint_2.md
  docs/meeting/PC2/sprint_3.md
Labels: Documentação

#49 Características da plataforma
  docs/planning/platform_features.md
Labels: Documentação, Dívida técnica

#52 New tasks analysis
  docs/use_context/tasks_analysis.md
Labels: Documentação

#53 Criação do doc da apresentação do PC2
  docs/_sidebar.md
  docs/meeting/PC2/pc2_presentation.md
Labels: Apresentação

#54 StoryBoard
  docs/assets/images/Storyboard.png
  docs/use_context/storyboards.md
Labels: Documentação

#55 Ajuste no tópico de conformidade
  docs/_sidebar.md
  docs/assets/css/home.css
  docs/assets/images/style_guide/a_vencer.png
  docs/assets/images/style_guide/assinado.png
  docs/assets/images/style_guide/config_de_sistema.png
  docs/assets/images/style_guide/controle_de_processos.png
  docs/assets/images/style_guide/expirado.png
  docs/assets/images/style_guide/login.png
  docs/assets/images/style_guide/menu.png
  docs/assets/images/style_guide/novidades.png
  docs/assets/images/style_guide/para_saber.png
  docs/assets/images/style_guide/pesquisa.png
  docs/assets/images/style_guide/prioridade.png
  docs/assets/images/style_guide/pros_fundo_azul.png
  docs/assets/images/style_guide/pros_fundo_preto.png
  docs/assets/images/style_guide/pros_fundo_vermelho.png
  docs/assets/images/style_guide/pros_num_azul.png
  docs/assets/images/style_guide/pros_num_preto.png
  docs/assets/images/style_guide/pros_num_vermelho.png
  docs/assets/images/style_guide/publicado.png
  docs/assets/images/style_guide/sair_do_sistema.png
  docs/assets/images/style_guide/selecao_de_unidade.png
  docs/assets/images/style_guide/sigiloso.png
  docs/assets/images/style_guide/simples.png
  docs/assets/images/style_guide/usuario.png
  docs/styling/style_guide.md
Labels: Apresentação, Documentação, Estilização

#56 Ponto de Controle 3
  docs/_sidebar.md
  docs/meeting/PC2/sprint_3.md
  docs/meeting/PC3/pc3_presentation.md
  docs/meeting/PC3/sprint_4.md
  docs/meeting/PC3/sprint_5.md
  docs/planning/project_planning.md
Labels: Apresentação

#60 Planejamento da avaliação do storyboard
  docs/_sidebar.md
  docs/assets/termo_de_consentimento_HTA.pdf
  docs/assets/termo_de_consentimento_storyboard.pdf
  docs/evaluation/storyboard/consent_form.md
  docs/evaluation/storyboard/planning.md
  docs/evaluation/task_analysis/consent_form.md
  docs/evaluation/task_analysis/planning.md
Labels: Documentação

#59 #57 Create planning documents
  docs/_sidebar.md
  docs/assets/termo_de_consentimento_HTA.pdf
  docs/evaluation/task_analysis/consent_form.md
  docs/evaluation/task_analysis/planning.md
Labels: Documentação
