Repository Interacao-Humano-Computador/2020.1-SEI, pull requests merged in 2020-09, with the labels that each got.

#14 Readme
  README.md
  docs/README.md
  docs/assets/images/logo.png
  docs/assets/images/logo.svg
  docs/assets/images/members/Hugo.jpeg
  docs/assets/images/members/Joao.jpg
  docs/assets/images/members/Leonardo.jpg
  docs/assets/images/members/Victor.jpg
  docs/index.html
Labels: Documentação, Estilização

#16 Estruturar wiki
  docs/README.md
  docs/_coverpage.md
  docs/_navbar.md
  docs/_sidebar.md
  docs/assets/css/home.css
  docs/assets/css/navbar.css
  docs/assets/images/logo.svg
  docs/assets/images/logo_black_mode.png
  docs/assets/images/logo_black_mode.svg
  docs/assets/images/word_mark.svg
  docs/assets/images/word_mark_black_mode.png
  docs/assets/images/word_mark_black_mode.svg
  docs/assets/images/word_mark_vertical.png
  docs/assets/images/word_mark_white_mode.png
  docs/evaluation/heuristic_evaluation.md
  docs/evaluation/project_general_principles.md
  docs/evaluation/usability_goals.md
  docs/index.html
  docs/planning/evaluated_sites.md
  docs/planning/platform_features.md
  docs/planning/project_planning.md
  docs/planning/team_planning.md
  docs/styling/accessibility.md
  docs/styling/style_guide.md
  docs/use_context/personas.md
  docs/use_context/storyboards.md
  docs/use_context/tasks_analysis.md
  docs/use_context/user_profiles.md
Labels: Documentação, Estilização

#21 Escrever documento sobre as ferramentas adotadas
  docs/planning/team_planning.md
Labels: Documentação

#27 Metodologia
  docs/planning/team_planning.md
Labels: Documentação

#28 Planejamento da equipe
  docs/assets/images/heatmap.png
  docs/planning/team_planning.md
Labels: Documentação

#29 Planejamento do projeto
  README.md
  docs/README.md
  docs/assets/css/home.css
  docs/assets/images/mayhew.jpg
  docs/planning/project_planning.md
  docs/planning/team_planning.md
Labels: Documentação

#32 Lista de sites avaliados
  docs/planning/evaluated_sites.md
Labels: Documentação

#33 Princípios gerais do projeto
  docs/evaluation/project_general_principles.md
Labels: Documentação

#34 Documentar as metas de usabilidade
  docs/evaluation/usability_goals.md
Labels: Documentação

#37 Documentar sprint 0 e sprint 1
  docs/_sidebar.md
  docs/meeting/PC1/sprint_0.md
  docs/meeting/PC1/sprint_1.md
  docs/meeting/PC2/sprint_2.md
  docs/planning/evaluated_sites.md
  docs/styling/accessibility.md
  docs/styling/style_guide.md
Labels: Documentação

#38 Documentar reunião com o professor
  docs/_sidebar.md
  docs/meeting/PC1/professor_meeting_1.md
Labels: Documentação

#39 apresentação do PC1
  docs/_sidebar.md
  docs/meeting/PC1/pc1_presentation.md
  docs/meeting/PC1/professor_meeting_1.md
Labels: Apresentação

#40 Atual guia de estilo do SEI
  docs/assets/atual_manual_de_identidade_visual.pdf
  docs/styling/accessibility.md
  docs/styling/style_guide.md
Labels: Documentação, Estilização
